const PressReleases = [
    {
        title: 'XRPH AI App Goes Live - Instant Multilingual Medical Guidance at Users&apos; Fingertips',
        img: '/press-releases/xrph-ai-app-goes-live.webp',
        link: 'https://www.prnewswire.com/news-releases/xrph-ai-app-goes-live--instant-multilingual-medical-guidance-at-users-fingertips-302372861.html',
        date: '2025-02-11',
    },
    {
        title: 'Amid Rising Costs, XRP Healthcare Prescription Savings Card Making a Difference at 68,000 Pharmacies Across America: A Game-Changer for Individuals and Organizations Alike',
        img: '/press-releases/xrphealthcare-prescription-savings-card.webp',
        link: 'https://www.prnewswire.com/news-releases/amid-rising-costs-xrp-healthcare-prescription-savings-card-making-a-difference-at-68-000-pharmacies-across-america-a-game-changer-for-individuals-and-organizations-alike-302291868.html',
        date: '2024-10-31',
    },
    {
        title: 'XRP Healthcare and Foventa Collaborate for Africa&apos;s Premier Lab Expo',
        img: '/press-releases/xrph-partnership-foventa.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-and-foventa-collaborate-for-africas-premier-lab-expo-302266027.html',
        date: '2024-10-03',
    },
    {
        title: 'XRP Healthcare Magazine Unveils Groundbreaking AI Development in 4th Issue, Featuring Elon Musk',
        img: '/magazines/xrp_healthcare_magazine_issue_4.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-magazine-unveils-groundbreaking-ai-development-in-4th-issue-featuring-elon-musk-302252413.html',
        date: '2024-09-19',
    },
    {
        title: 'XRP Healthcare Enters the Limitless World of AI',
        img: '/press-releases/XRPH_chatbot.jpg',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-enters-the-limitless-world-of-ai-302242671.html',
        date: '2024-09-10',

    },
    {
        title: 'XRP Healthcare Secures Major Media Partnership with Global Exhibition Titans',
        img: '/press-releases/xrphealthcare-partnership.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-secures-major-media-partnership-with-global-exhibition-titans-302207104.html',
        date: '2024-07-26',
    },
    {
        title: 'XRP Healthcare Halts New Staking of XRPH Token to Preserve Finite Supply, Shifts Focus to Real-World Healthcare Ventures',
        img: '/press-releases/xrphealthcare-halts-staking.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-halts-new-staking-of-xrph-token-to-preserve-finite-supply-shifts-focus-to-real-world-healthcare-ventures-302203541.html',
        date: '2024-07-23',
    },
    {
        title: 'XRP Healthcare LLC Successfully Registers Trademark in the UAE, Strengthening Global Expansion and Legal Compliance',
        img: '/press-releases/xrph-uae.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-llc-successfully-registers-trademark-in-the-uae-strengthening-global-expansion-and-legal-compliance-302195390.html',
        date: '2024-07-12',
    },
    {
        title: 'XRP Healthcare: Helping to Transform HIV and AIDS Care with Innovative Prescription Savings Solutions',
        img: '/press-releases/xrp-healthcare-savings-card.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-helping-to-transform-hiv-and-aids-care-with-innovative-prescription-savings-solutions-302186439.html',
        date: '2024-07-01',
    },
    {
        title: 'After Just 18 Months, Is XRP Healthcare (XRPH) One of the Fastest Growing Companies on the Blockchain?',
        img: '/press-releases/xrp_healthcare_infographic.webp',
        link: 'https://www.prnewswire.com/news-releases/after-just-18-months-is-xrp-healthcare-xrph-one-of-the-fastest-growing-companies-on-the-blockchain-302179720.html',
        date: '2024-06-24',
    },
    {
        title: 'XRP Healthcare Magazine Issue 3: Featuring Ugandan Innovator Peter Waiswa, NHS Collaborator ISANSYS, Ehlers-Danlos Society & Top 10 African Hospitals',
        img: '/magazines/xrp_healthcare_magazine_issue_3.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-magazine-issue-3-featuring-ugandan-innovator-peter-waiswa-nhs-collaborator-isansys-ehlers-danlos-society--top-10-african-hospitals-302173663.html',
        date: '2024-06-17',
    },
    {
        title: 'XRP Healthcare Welcomes 10 Billion Dollar M&A Specialist Whitney Lynn to Head Africa Expansion',
        img: '/press-releases/xrp_healthcare_whitney_lynn.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-welcomes-10-billion-dollar-ma-specialist-whitney-lynn-to-head-africa-expansion-302167726.html',
        date: '2024-06-10',
    },
    {
        title: 'XRP Healthcare Stops XRP to XRPH Swap Facility, Ensuring Token Scarcity on June 7th',
        img: '/press-releases/xrph-stops-swap.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-stops-xrp-to-xrph-swap-facility-ensuring-token-scarcity-on-june-7th-302155739.html',
        date: '2024-05-27',
    },
    {
        title: 'XRP Healthcare Sponsors The Ehlers-Danlos Society, with Vital Support via its Prescription Savings Card',
        img: '/press-releases/xrph-ehlers.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-sponsors-the-ehlers-danlos-society-with-vital-support-via-its-prescription-savings-card-302146868.html',
        date: '2024-05-16',
    },
    {
        title: 'XRP Healthcare Solidifies Presence in Uganda with Trademark Registration Success',
        img: '/press-releases/xrph_uganda.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-solidifies-presence-in-uganda-with-trademark-registration-success-302143051.html',
        date: '2024-05-13',
    },
    {
        title: 'Renowned Industry Expert Peter Kyobe Waiswa Joins XRP Healthcare to transform Private Healthcare in Uganda',
        img: '/press-releases/xrph_kyobe_waiswa.webp',
        link: 'https://www.prnewswire.com/news-releases/renowned-industry-expert-peter-kyobe-waiswa-joins-xrp-healthcare-to-transform-private-healthcare-in-uganda-302117285.html',
        date: '2024-04-16',
    },
    {
        title: 'XRP Healthcare Unveils Revolutionary Swap Facility in Open-Source XRPH Wallet, Encouraging Autonomy Across XRPL Projects',
        img: '/press-releases/xrphealthcare_swap.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-unveils-revolutionary-swap-facility-in-open-source-xrph-wallet-encouraging-autonomy-across-xrpl-projects-302112276.html',
        date: '2024-04-10',
    },
    {
        title: 'XRP Healthcare move forward as one entity for African M&A venture',
        img: '/press-releases/xrph_african_venture.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-move-forward-as-one-entity-for-african-ma-venture-302101760.html',
        date: '2024-03-28',
    },
    {
        title: 'XRP Healthcare Partner with NHS collaborator Isansys Lifecare to Revolutionize Healthcare Services in Uganda',
        img: '/press-releases/xrph_isansys.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-partner-with-nhs-collaborator-isansys-lifecare-to-revolutionize-healthcare-services-in-uganda-302097744.html',
        date: '2024-03-25',
    },
    {
        title: 'XRP Healthcare Announces Strategic Partnership with Expogroup to Expand Presence in Africa',
        img: '/press-releases/xrp_expogroup.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-announces-strategic-partnership-with-expogroup-to-expand-presence-in-africa-302095181.html',
        date: '2024-03-21',
    },
    {
        title: 'XRP Healthcare release 2nd issue of its highly anticipated Magazine',
        img: '/magazines/xrp_healthcare_magazine_issue_2.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-release-2nd-issue-of-its-highly-anticipated-magazine-302092751.html',
        date: '2024-03-19',
    },
    {
        title: 'XRP Healthcare Advances as XRPL Validator - Strengthening Crypto Transparency',
        img: '/press-releases/21.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-advances-as-xrpl-validator---strengthening-crypto-transparency-302034187.html',
        date: '2024-01-15',
    },
    {
        title: 'XRP Healthcare Appoints Digital Healthcare Evangelist and Isansys Founder Keith Errey as Strategic Advisor',
        img: '/africa/keith-errey.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-appoints-digital-healthcare-evangelist-and-isansys-founder-keith-errey-as-strategic-advisor-302021008.html',
        date: '2023-12-21',
    },
    {
        title: "XRP Healthcare takes Ripple's Lead with Expansion into Dubai and Middle East",
        img: '/press-releases/12.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-takes-ripples-lead-with-expansion-into-dubai-and-middle-east-301971208.html',
        date: '2023-10-30',
    },
    {
        title: 'XRP Healthcare Expands Its Reach into Africa by Listing on Coinstore',
        img: '/press-releases/10.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-expands-its-reach-into-africa-by-listing-on-coinstore-301952025.html',
        date: '2023-10-10',
    },
    {
        title: 'XRP Healthcare List on MEXC strategically positioning itself for imminent Crypto Bull Run',
        img: '/press-releases/8.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-list-on-mexc-strategically-positioning-itself-for-imminent-crypto-bull-run-301931211.html',
        date: '2023-09-19',
    },
    {
        title: 'Introducing the XRP Healthcare Decentralized Mobile Wallet: Empowering Users with Unparalleled Control, Savings, and Rewards',
        img: '/press-releases/7.webp',
        link: 'https://www.prnewswire.com/news-releases/introducing-the-xrp-healthcare-decentralized-mobile-wallet-empowering-users-with-unparalleled-control-savings-and-rewards-301927163.html#:~:text=The%20XRPH%20Wallet%20is%20a,secure%20but%20also%20entirely%20anonymous',
        date: '2023-09-14',
    },
    {
        title: 'XRP Healthcare (XRPH) Will Be Listed On Global Crypto Exchange LBank August 16th 11:00 UTC 2023',
        img: '/press-releases/6.webp',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-xrph-will-be-listed-on-global-crypto-exchange-lbank-august-16th-1100-utc-2023-301899500.html',
        date: '2023-08-14',
    },
    {
        title: 'XRP Healthcare and Spiritus Medical Partner to Revolutionize Healthcare in Africa',
        img: '/press-releases/5.webp',
        link: 'https://www.prnewswire.co.uk/news-releases/xrp-healthcare-and-spiritus-medical-partner-to-revolutionize-healthcare-in-africa-301891977.html',
        date: '2023-08-03',
    },
    {
        title: 'XRP Healthcare Africa partners with FasterCapital run by Forbes top-rated investor Hesham Zreik',
        img: '/press-releases/fastercapital.jpg',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-africa-partners-with-fastercapital-run-by-forbes-top-rated-investor-hesham-zreik-301803680.html',
        date: '2023-04-21',
    },
    {
        title: 'XRP Healthcare enters Africa to revolutionize the multi-billion-dollar Healthcare industry',
        img: '/press-releases/media/xrph-africa.png',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-enters-africa-to-revolutionize-the-multi-billion-dollar-healthcare-industry-301786257.html',
        date: '2023-03-30',
    },
    {
        title: 'XRPH Joins Elite Cryptocurrencies on BitMart Exchange opening to millions of U.S consumers',
        img: '/press-releases/2.webp',
        link: 'https://www.prnewswire.co.uk/news-releases/xrph-joins-elite-cryptocurrencies-on-bitmart-exchange-opening-to-millions-of-us-consumers-301770743.html',
        date: '2023-03-14',
    },
    {
        title: 'XRP Healthcare Partners with \'United Networks of America\' with access to 120 million members',
        img: '/press-releases/savings-coupon.jpg',
        link: 'https://www.prnewswire.com/news-releases/xrp-healthcare-partners-with-united-networks-of-america-with-access-to-120-million-members-301765076.html',
        date: '2023-03-08',
    },
    {
        title: 'XRP Healthcare celebrates its first listing on Bitrue',
        img: '/xrph-logos/logo-v.png',
        link: 'https://www.prnewswire.co.uk/news-releases/xrp-healthcare-celebrates-its-first-listing-on-bitrue-301734504.html',
        date: '2023-01-31',
    },
    {
        title: 'XRPH announces new listing on Bitrue Exchange',
        img: '/press-releases/1.webp',
        link: 'https://www.prnewswire.com/news-releases/xrph-announces-new-listing-on-bitrue-exchange-301730600.html',
        date: '2023-01-26',
    },
    {
        title: 'XRP Healthcare – The first Decentralized Pharma & Healthcare marketplace built on the XRP Ledger',
        img: '/xrph-logos/logo-v.png',
        link: 'https://www.prnewswire.co.uk/news-releases/xrp-healthcare---the-first-decentralized-pharma--healthcare-marketplace-built-on-the-xrp-ledger-301725072.html',
        date: '2023-01-19',
    }
]
export {PressReleases}